apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: topolvm.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  labels:
    kubernetes.io/hostname: hpe2ocp4lab.attlocal.net
  name: pvc-0a49d3c2-389b-4759-83e2-988cfdf28661
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    name: centos-stream9-8c82c364caed
    namespace: openshift-virtualization-os-images
  csi:
    driver: topolvm.io
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1785992964464-1553-topolvm.io
    volumeHandle: f76fd445-7591-4548-964b-c6565c4f265b
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.topolvm.io/node
          operator: In
          values:
          - hpe2ocp4lab.attlocal.net
  persistentVolumeReclaimPolicy: Delete
  storageClassName: lvms-vg1
  volumeMode: Block
