apiVersion: v1
kind: Namespace
metadata:
  name: ocp4lab1-spoke
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-clusterinstance-role
  namespace: ocp4lab1-spoke
rules:
  - apiGroups:
      - siteconfig.open-cluster-management.io
    resources:
      - clusterinstances
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-clusterinstance-rolebinding
  namespace: ocp4lab1-spoke
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-clusterinstance-role
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
