apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: topolvm.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  labels:
    kubernetes.io/hostname: hpe2ocp4lab.attlocal.net
  name: pvc-5f6d8244-0433-4b37-b863-ce00c82a45c7
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    name: fedora-1217dcc8c58d
    namespace: openshift-virtualization-os-images
  csi:
    driver: topolvm.io
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1785992964464-1553-topolvm.io
    volumeHandle: 8fd34b94-a857-403e-92a9-c7ab2af4d445
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.topolvm.io/node
          operator: In
          values:
          - hpe2ocp4lab.attlocal.net
  persistentVolumeReclaimPolicy: Delete
  storageClassName: lvms-vg1
  volumeMode: Block
