apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: topolvm.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  labels:
    kubernetes.io/hostname: hpe2ocp4lab.attlocal.net
  name: pvc-b2602382-1910-4e79-a959-31c161580bb6
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    name: rhel10-c5b97492a6e3
    namespace: openshift-virtualization-os-images
  csi:
    driver: topolvm.io
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1785992964464-1553-topolvm.io
    volumeHandle: bed3656d-0255-45bc-a537-7fc40e1bffdc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.topolvm.io/node
          operator: In
          values:
          - hpe2ocp4lab.attlocal.net
  persistentVolumeReclaimPolicy: Delete
  storageClassName: lvms-vg1
  volumeMode: Block
