apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: topolvm.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  labels:
    kubernetes.io/hostname: hpe2ocp4lab.attlocal.net
  name: pvc-3f81775a-583e-4c78-a4ce-538a59e1c5c3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    name: rhel8-c6a08edc555b
    namespace: openshift-virtualization-os-images
  csi:
    driver: topolvm.io
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1785992964464-1553-topolvm.io
    volumeHandle: a27caa9e-0d8b-4904-a340-b007b2e7d254
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.topolvm.io/node
          operator: In
          values:
          - hpe2ocp4lab.attlocal.net
  persistentVolumeReclaimPolicy: Delete
  storageClassName: lvms-vg1
  volumeMode: Block
