apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: topolvm.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  labels:
    kubernetes.io/hostname: hpe2ocp4lab.attlocal.net
  name: pvc-413d10ab-5e53-46f7-abb4-1825a9e7560e
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgredb-tekton-results-postgres-0
    namespace: openshift-pipelines
  csi:
    driver: topolvm.io
    fsType: xfs
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1785992964464-1553-topolvm.io
    volumeHandle: 699135d6-23e1-458d-a0b7-2fa361fa4814
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.topolvm.io/node
          operator: In
          values:
          - hpe2ocp4lab.attlocal.net
  persistentVolumeReclaimPolicy: Delete
  storageClassName: lvms-vg1
  volumeMode: Filesystem
